name: triqui_flutter
description: Juego de Triqui para aprender Flutter

# Versión del SDK de Dart necesaria
environment:
  sdk: '>=2.19.0 <4.0.0'

# Dependencias del proyecto
dependencies:
  flutter:
    sdk: flutter
  
  # Material Design (UI components de Google)
  cupertino_icons: ^1.0.2

# Dependencias de desarrollo
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# Configuración de Flutter
flutter:
  uses-material-design: true
